# extend compose stack with mongo-express (gui admin tool for mongo), for test/development purposes
#
version: '3'

services:

  mongo-express:
    image: mongo-express
    ports:
      - 4567:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb