# this is the demo docker compose; setup a stack for demonstration, based on the production config
#
# run demo:
#    docker-compose -f docker-compose.yaml -f docker-compose.demo.yaml up -d
#

version: '3'

services:

  arena-web: # create a container named "arena-web"; other service containers in this file can resolve its name (arena-web)
    image: arenaxrorg/arena-web-core:${ARENA_WEB_CORE_VERSION:-latest} # pulls from https://hub.docker.com/repository/docker/arenaxr/arena-web-core
    volumes:
      - ./conf/demo/arena-web.conf:/etc/nginx/conf.d/arena-web.conf:ro # mount nginx config
      - ./store:/usr/share/nginx/html/store:ro # mount store files
      - ./conf/demo/arena-web-conf:/usr/share/nginx/html/conf # arena client code conf
      - account-static-content:/usr/share/nginx/html/user/static:ro # serve account static files
    ports:
      - "80:80" # map port 80 on the host to port 80 on the container
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'" # reload certificates every 6h
    restart: unless-stopped # service will respawn unless we tell docker to stop it

  mongodb:
    image: mongo:${MONGO_VERSION:-latest} # pull from https://hub.docker.com/_/mongo/    
    restart: unless-stopped

  arena-persist:
    image: arenaxrorg/arena-persist:${ARENA_PERSIST_VERSION:-v1.0.0} # pulls from https://hub.docker.com/repository/docker/arenaxrorg/arena-persist
    restart: unless-stopped

  arena-account:
    image: arenaxrorg/arena-account:${ARENA_ACCOUNT_VERSION:-latest} # pulls from https://hub.docker.com/repository/docker/arenaxrorg/arena-account
    volumes:
      - ./conf/account-settings.py:/usr/src/app/arena_account/settings.py:ro
      - account-static-content:/usr/src/app/static # static content
      - ./data/account:/usr/src/app/db # account db
    env_file:
      - .env
      - secret.env
    restart: unless-stopped

  mqtt:
    image: arenaxrorg/arena-broker:${ARENA_BROKER_VERSION:-latest} # pulls from https://hub.docker.com/repository/docker/arenaxrorg/arena-broker
    ports:
      - 8083:8083/tcp # mqtt-wss
      - 8883:8883/tcp # mqtt-tls
    restart: unless-stopped

  store:
    # version #, settings, and full inline script from /storemng must match ./init-utils/filebrowserScriptToHash.js values
    image: "filebrowser/filebrowser:${ARENA_FILESTORE:-latest}"  # pulls from https://hub.docker.com/r/filebrowser/filebrowser

volumes:
  account-static-content:
