name: Update demo branch
on:
  workflow_dispatch:
  push:

jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: master
          branches: demo master
          files: demo.sh build-arena-core.sh cleanup.sh gen-root-token.sh init-certs.sh init-config.sh update-custom-website.sh init.env init.sh VERSION docker-compose.yaml docker-compose.demo.yaml conf-templates/*
          exclude: conf-templates/localdev conf-templates/prod conf-templates/staging