name: Update prod branch
on:
  workflow_dispatch:
  push:

jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@8a8a05b3f22dec3acf38c6af4c7074b39911e586 # v1.3.0
        env:
          key: master
          branches: prod master
          files: backup.sh build-arena-core.sh  cleanup.sh gen-root-token.sh init-certs.sh init-config.sh init.env init.sh update-custom-website.sh prod.sh prepro.sh VERSION VERSION.preprod docker-compose.yaml docker-compose.prod.yaml conf-templates/*
          exclude: conf-templates/localdev conf-templates/demo conf-templates/staging